### ISSUE TITLE
Plugin wont load on 1.14.4

### ISSUE THREAD

**Issue by Hamstie1** [SpillereNO/BlowableObsidians#19]
I tried installing the plugin on my server and I am getting an error of the plugin, not loading. I've tried to update java and it still not working.

```
[20:53:08] [Server thread/ERROR]: Could not load 'plugins\BlowableObsidians (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:261) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by anzure** [comment]
**Open BlowableObsidians.jar in 7zip or WinRar, and edit plugin.yml:
- change api-version from 1.15 to 1.14.**

I will attempt to make a permanent fix. I think this is caused on 1.14, and maybe also 1.13.
